name = "ArviZPlots"
uuid = "8a1e6714-0cb5-4d96-8483-49ba731f3e3e"
authors = ["Seth Axen <seth.axen@gmail.com> and contributors"]
version = "0.1.0"

[deps]
ArviZ = "131c737c-5715-5e2e-ad31-c244f01c1dc7"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
RecipesPipeline = "01d81517-befc-4cb6-b9ec-a95719d0359c"

[compat]
ArviZ = "0.4"
KernelDensity = "0.5, 0.6"
RecipesBase = "1"
RecipesPipeline = "0.2, 0.3"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
